// Generated by CoffeeScript 1.4.0
(function() {
  var d, helpers;

  helpers = require('helpers');

  d = require('./index');

  exports.nohammer = function(test) {
    var cnt, hammerme, hammermed;
    cnt = 0;
    hammerme = function(arg) {
      return cnt += arg;
    };
    hammermed = d.decorate(d.makeNoHammer({
      waittime: 50
    }), hammerme);
    hammermed(1);
    hammermed(1);
    hammermed(1);
    hammermed(3);
    return helpers.wait(75, function() {
      hammermed(1);
      test.equals(cnt, 5);
      return test.done();
    });
  };

}).call(this);
